export const demoBasketItems = [
  {
    id: "1",
    productId: "milk-tnuva-3-1l",
    name: "חלב 3%",
    quantity: 2,
    emoji: "🥛",
    subtitle: "תנובה • 1 ליטר",
    brand: "תנובה",
    unit: "1 ליטר",
    barcode: "729000000001",
  },
  {
    id: "2",
    productId: "bread-white-standard",
    name: "לחם אחיד",
    quantity: 1,
    emoji: "🍞",
    subtitle: "מאפייה • 1 יחידה",
    brand: "מאפייה",
    unit: "1 יחידה",
    barcode: "729000000004",
  },
  {
    id: "3",
    productId: "eggs-l-12",
    name: "ביצים L",
    quantity: 1,
    emoji: "🥚",
    subtitle: "ללא מותג • 12 יחידות",
    brand: "ללא מותג",
    unit: "12 יחידות",
    barcode: "729000000003",
  },
];