import { Product } from "../../features/products/types";

export const demoProducts: Product[] = [
  {
    productId: "milk-tnuva-3-1l",
    name: "חלב 3%",
    brand: "תנובה",
    unit: "1 ליטר",
    barcode: "729000000001",
    emoji: "🥛",
    category: "dairy",
  },
  {
    productId: "milk-yotvata-3-1l",
    name: "חלב 3%",
    brand: "יוטבתה",
    unit: "1 ליטר",
    barcode: "729000000002",
    emoji: "🥛",
    category: "dairy",
  },
  {
    productId: "eggs-l-12",
    name: "ביצים L",
    brand: "ללא מותג",
    unit: "12 יחידות",
    barcode: "729000000003",
    emoji: "🥚",
    category: "eggs",
  },
  {
    productId: "bread-white-standard",
    name: "לחם אחיד",
    brand: "מאפייה",
    unit: "1 יחידה",
    barcode: "729000000004",
    emoji: "🍞",
    category: "bakery",
  },
  {
    productId: "greek-yogurt-danone-130g",
    name: "יוגורט יווני 6.5%",
    brand: "דנונה",
    unit: "130 גרם",
    barcode: "729000000005",
    emoji: "🥣",
    category: "dairy",
  },
  {
    productId: "tomatoes-kg",
    name: "עגבניות",
    brand: "טרי",
    unit: 'לק"ג',
    barcode: "729000000006",
    emoji: "🍅",
    category: "vegetables",
  },
  {
    productId: "cucumbers-kg",
    name: "מלפפון",
    brand: "טרי",
    unit: 'לק"ג',
    barcode: "729000000007",
    emoji: "🥒",
    category: "vegetables",
  },
  {
    productId: "cottage-tnuva-250g",
    name: "קוטג׳ 5%",
    brand: "תנובה",
    unit: "250 גרם",
    barcode: "729000000008",
    emoji: "🧀",
    category: "dairy",
  },
  {
    productId: "yellow-cheese-200g",
    name: "גבינה צהובה",
    brand: "עמק",
    unit: "200 גרם",
    barcode: "729000000009",
    emoji: "🧀",
    category: "dairy",
  },
  {
    productId: "rice-ossem-1kg",
    name: "אורז",
    brand: "אסם",
    unit: '1 ק"ג',
    barcode: "729000000010",
    emoji: "🍚",
    category: "pantry",
  },
  {
    productId: "pasta-ossem-500g",
    name: "פסטה",
    brand: "אסם",
    unit: "500 גרם",
    barcode: "729000000011",
    emoji: "🍝",
    category: "pantry",
  },
  {
    productId: "chicken-breast-kg",
    name: "חזה עוף",
    brand: "טרי",
    unit: 'לק"ג',
    barcode: "729000000012",
    emoji: "🍗",
    category: "meat",
  },
  {
    productId: "bananas-kg",
    name: "בננות",
    brand: "טרי",
    unit: 'לק"ג',
    barcode: "729000000013",
    emoji: "🍌",
    category: "fruit",
  },
  {
    productId: "apples-kg",
    name: "תפוחים",
    brand: "טרי",
    unit: 'לק"ג',
    barcode: "729000000014",
    emoji: "🍎",
    category: "fruit",
  },
  {
    productId: "olive-oil-750ml",
    name: "שמן זית",
    brand: "יד מרדכי",
    unit: '750 מ"ל',
    barcode: "729000000015",
    emoji: "🫒",
    category: "pantry",
  },
];